Repository Maksasj/UFO-List, pull requests merged in 2022-12, with the labels that each got.

#10 Extracted BUILD.md file
  BUILD.md
  README.md
Labels: documentation

#9 Configure tests with gclados
  .vscode/settings.json
  CMakeLists.txt
  README.md
  cmake-modules/gclados.cmake
  include/gclados/arrayPredicates.h
  include/gclados/boolPredicates.h
  include/gclados/bytePredicates.h
  include/gclados/colors.h
  include/gclados/dynamicArray.h
  include/gclados/fileUtils.h
  include/gclados/floatPredicates.h
  include/gclados/gclados.h
  include/gclados/ioutils.h
  include/gclados/logging.h
  include/gclados/mutils.h
  include/gclados/notPredicate.h
  include/gclados/numberPredicates.h
  include/gclados/panic.h
  include/gclados/predicate.h
  include/gclados/predicateNamespace.h
  include/gclados/snapshots.h
  include/gclados/statement.h
  include/gclados/statementContext.h
  include/gclados/stringPredicates.h
  include/gclados/test.h
  include/gclados/testSuite.h
  include/html-generator/html-generator.h
  lib/libgclados.a
  modules/html-generator/CMakeLists.txt
  modules/html-generator/test/CMakeLists.txt
  modules/html-generator/test/entry.c
  modules/html-generator/test/html-generator.test.c
Labels: configuration

#11 Redesigned core html-generator API
  CMakeLists.txt
  cmake-modules/gclados.cmake
  include/html-generator/html-generator.h
  main/main.c
  modules/html-generator/src/CMakeLists.txt
  modules/html-generator/src/freeNode.c
  modules/html-generator/src/html-generator.c
  modules/html-generator/src/initNode.c
  modules/html-generator/test/CMakeLists.txt
  modules/html-generator/test/entry.c
  modules/html-generator/test/html-generator.test.c
  modules/html-generator/test/initNode.test.c
Labels: enhancement, configuration

#15 Configured vscode build task and debugger
  .default-vscode/default-launch.json
  .default-vscode/default-settings.json
  .default-vscode/default-tasks.json
  .gitignore
  BUILD.md
  CONTRIBUTING.md
  README.md
  make.bat
Labels: configuration

#17 Kamile API functions
  .vscode/settings.json
  include/html-generator/html-generator.h
  modules/html-generator/src/freeNode.c
  modules/html-generator/src/initNode.c
  modules/html-generator/src/pushChildrenNode.c
  modules/html-generator/src/pushStringLiteral.c
  modules/html-generator/test/CMakeLists.txt
  modules/html-generator/test/entry.c
  modules/html-generator/test/initNode.test.c
  modules/html-generator/test/pushChildrenNode.test.c
  modules/html-generator/test/pushStringLiteral.test.c
  modules/html-generator/test/testUtils.c
  modules/html-generator/test/testUtils.h
Labels: enhancement

#19 Write documentation for html-generator
  include/html-generator/html-generator.h
  main/CMakeLists.txt
  modules/html-generator/src/pushChildrenNode.c
Labels: documentation
